### ISSUE TITLE
Popover and tooltips not working

### ISSUE THREAD

**Issue by ReindDooyeweerd** [noreading/bootstrap5-webpack-boilerplate#82]
Just came by this project looking for a solution why i can't get the tooltips and popovers aren't working and found out they don't work on this project also. Any idea why they aren't working on your project?

**Comment by noreading** [comment]
The bootstrap documentation says "Tooltips are opt-in for performance reasons, so you must initialize them yourself.". The same is true for popover elements and toasts.

I will add some configuration to the boilerplate for the next version (which is coming today), so that it's easier to use for those cases. It will have a config to enable / disable additional features.

**Comment by noreading** [comment]
Here we go. Check out the new version and you'll have all the features ready to be used.

https://github.com/noreading/bootstrap5-webpack-boilerplate/releases/tag/v1.2.0
