### ISSUE TITLE
watch index.html in the browser

### ISSUE THREAD

**Issue by alandolsi** [noreading/bootstrap5-webpack-boilerplate#83]
Hi,

Wehn I run npm run dev, the browser do not open the index.html, is there any extra configuration for that??

Thank you for the repository .

**Comment by noreading** [comment]
Hi,

there is no webpack-devserver included right now, but I'll have a look into that.
You can just open the index.html in any browser for now.

**Comment by noreading** [comment]
@alandolsi Hi there!

I worked on a new version of the boilerplate with some features that you'll like.

- Hot reloading in your browser (so you see changes without a page reload)
- A new build system, that generates everything in the `public`folder, including copying assets, so that you can just upload or sync those files and can't miss anything anymore.

It would be great if you could test the new setup, before I release it for everybody. 👍 

Just check out the branch "v2" using git or download the zip folder [here](https://github.com/noreading/bootstrap5-webpack-boilerplate/archive/refs/heads/v2.zip).

Best,
Dominik

**Comment by alandolsi** [comment]
@noreading Hi Diminik, Thank you for your work and effort, I wil test the V2 👍

**Comment by htrex** [comment]
Hi @noreading,
I'm trying the V2 branch, I confirm that it automatically opens localhost:9090 in the browser, but it doesn't auto-reload the page when index.html is changed. I'm at my first steps with webpack, would you please suggest how to watch for index.html changes and enable a browser auto reload?

**Comment by noreading** [comment]
@htrex Indeed ... it does update when JS or CSS is changed, but not when the HTML is changed. I'll have a look at this. May be it's just a configuration issue.

**Comment by noreading** [comment]
@htrex I added another webpack dev server directive, that seems to work. Can you test again on your system, please?
